### ISSUE TITLE
paginate problem

### ISSUE THREAD

**Issue by cauyyl** [tokict/react-native-comments#14]
I have 5 comments, and i set 5 comments per page. I still got tow pages,the first page contains 0 comment,and the second page contains 5 comments.

**Comment by tokict** [comment]
What is a page? What does this component have to do with results from your backend?

**Comment by cauyyl** [comment]
> What is a page? What does this component have to do with results from your backend?

I means 'show more', if i have 6 comments, the component load 1 comment first, then click 'show more' , all comment loaded. I have changed the code of your component, myabe i had created a new bug here? (I'm so sorry for my English expression)

I found the question is related with FlstList's property initialNumToRender, i'm trying to handle it

**Comment by cauyyl** [comment]
I found the question is related with FlstList's property initialNumToRender
