### ISSUE TITLE
Type Error: this.getStyle is not a function

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [tokict/react-native-comments#15]
Took you example app and tried to integrate this into my project and i got this error.Tried with a clean project and got the same error as well. 

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-22 at 11 45 27](https://user-images.githubusercontent.com/14100765/71324730-a4720000-24b0-11ea-94d6-bef4b50b5b78.png)

**Comment by imanodaysoffdotcom** [comment]
Got it to work by adding that function to the index.js file 

  getStyle(name){
    return this.props.styles && this.props.styles[name] ? this.props.styles[name] : {};
  }

**Comment by tokict** [comment]
Glad you sorted it out. I'll update the example app

**Comment by reiui9** [comment]
@imanodaysoffdotcom Thanks. I solved it too.
