### ISSUE TITLE
When the keyboard is first responder the Submit button should be tapped twice to add the comment

### ISSUE THREAD

**Issue by fighterinthewind** [tokict/react-native-comments#4]
When I add some text in the text input and the keyboard is shown, I should tap Submit button twice to add the comment - could you fix it just with one tap, please?
Thanks!

"react": "16.3.1",
"react-native": "0.55.2"
 iOS version: 11.3

**Comment by tokict** [comment]
Add keyboardShouldPersistTaps="always" to your Scroll list in which you render the component. I have add it to example and the new Sample app in the repo
