### ISSUE TITLE
How to disable the child comments/replies of a particular comment?

### ISSUE THREAD

**Issue by TechSatya** [tokict/react-native-comments#5]
I don't want the child replies for which I have tried removing out this thing from the index.js file, but It's more confusing and find it a bit complicated.

So help me out, please.

**Comment by tokict** [comment]
So you don't want replying option at all? If this is the case, I can add a config option to disable them completely. Just let me know if I understood correctly

**Comment by TechSatya** [comment]
Thank you for your so early response.
I have solved this by commenting out the related part of it in `renderComment(c) {}` function in index.js file.
I commented out after the `{this.generateComment(item)}` line.

I need an enhancement on "Edit, Copy, Delete, Report" things of a comment upon onLongPress of it.
So can it be doable??
