### ISSUE TITLE
Enhancement or adding of "Edit, Copy, Delete, Report" things for a comment upon onLongPress of it.

### ISSUE THREAD

**Issue by TechSatya** [tokict/react-native-comments#6]
It would be helpful to everyone adding "Copy, Delete, Report" on the comments.

So onLongPress of a comment, it should appear a list of actions where "Edit, Copy, Delete, Report" options with their functionalities.

So is it doable??

**Comment by tokict** [comment]
You can already copy natively and there is a report button there. I will add delete option though.
On long press is not intuitive and users would not figure out that this is the way to get to menu so I will make delete a button on the edit dialog.

Im basically copying Facebook comments here as they have all best practices implemented

**Comment by TechSatya** [comment]
Exactly, what I wanted you to follow through that's what Facebook's comment, because It's too simple by UI and gives many functionalities on long press only. We don't find many clumsy things in its UI.
So I was telling you to keep everything in onLongPress.

And the Report functionality can't be un-do after it's reported.

Also, it would be more intuitive if the edit functionality comes under the same comment input bar.

**Comment by tokict** [comment]
Menu has been added on long press.
If the delete or report action has been provided it will display appropriate buttons. If the user can edit, it will display edit button. 

The unreport is possible. It is the same action as report. You need to unreport it on the backend and refresh comments to reflect (take a look at reportedExtractor whish has a job of determining is the comment reported )

**Comment by TechSatya** [comment]
Thank you :) 
So how will I get that menu?
Can I get the whole updated things?
You can attach here those js files too.

**Comment by tokict** [comment]
Long press. Its in the npm repo. just update teh dependencies
