### ISSUE TITLE
How to disable the pagination such as "Show previous" and "Show more" permanently and render the whole comments at a time?

### ISSUE THREAD

**Issue by TechSatya** [tokict/react-native-comments#7]
I want to disable the pagination permanently and render the whole comments at a time.
Please help!!

Thank you.

**Comment by tokict** [comment]
I will add this and other features in a day or two/. However, if you have a lot of comments, that is not a good idea

**Comment by TechSatya** [comment]
Thank you :)
I have a suggestion regarding this. You can show a maximum of 2 comments, then the total no. of comments will be counted and will be shown in a line like '11 comments' above the TextInput and on clicking upon this line there will open a modal under which all the comments plus the TextInput will be shown.
(It's exactly like facebook, you can refer and design accordingly.)

**Comment by tokict** [comment]
Yust omit providing paginateAction and it will hide pagination. Also, if you omit replyAction or likeAction, it will hide those functionalities.

To display all comments, just send them all to the library and it will display 999 of them

**Comment by tokict** [comment]
Isnt this exactly how it works now except that its not a modal?

**Comment by TechSatya** [comment]
I tried out using your solution, but unfortunately, I just got only the shown comments by default but not the previous comments.

**Comment by tokict** [comment]
Component renders whatever data you send it under data prop. If you want
all comments to render, send it all comments from backend. There is no
previous or next comments in this case
